name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        npm install -g pkg
    - name: Create Asar Binary
      run: | 
        npm pack @electron/asar
        tar -xzf ./*.tgz
        ls
        cd package
        ls
    - name: Create PyInstaller Binary
      run: |
        pyinstaller Discord\ Legacy\ Patcher.py --onefile
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Discord Legacy Patcher
        path: /Users/runner/work/Discord-Legacy-Patcher/Discord-Legacy-Patcher/dist/Discord\ Legacy\ Patcher

